import mammoth from 'mammoth';
import JSZip from 'jszip';
import ommlXsltRaw from './xsd/OMML2MML.XSL?raw';

async function preprocessDocx(arrayBuffer) {
  const zip = new JSZip();
  await zip.loadAsync(arrayBuffer);

  const docXmlFile = zip.file("word/document.xml");
  if (!docXmlFile) {
    return { buffer: arrayBuffer, mathMap: new Map() };
  }

  const xmlString = await docXmlFile.async("string");
  
  const parser = new DOMParser();
  const doc = parser.parseFromString(xmlString, "application/xml");

  const xsltDoc = parser.parseFromString(ommlXsltRaw, "application/xml");
  const xsltProcessor = new XSLTProcessor();
  xsltProcessor.importStylesheet(xsltDoc);

  const mathMap = new Map();
  let mathCounter = 0;

  // Find all <m:oMath> nodes
  const mathNodes = Array.from(doc.getElementsByTagName("m:oMath"));

  for (const mathNode of mathNodes) {
    const resultFragment = xsltProcessor.transformToFragment(mathNode, document);
    
    if (resultFragment) {
      const div = document.createElement("div");
      div.appendChild(resultFragment);
      
      // Wrap the generated MathML in the standard <math> tag
      const mathmlString = `<math xmlns="http://www.w3.org/1998/Math/MathML">${div.innerHTML}</math>`;
      const mathId = `[[MATH_${mathCounter++}]]`;
      mathMap.set(mathId, mathmlString);

      // Create a plain text w:t node with the placeholder
      const wNamespace = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
      const runNode = doc.createElementNS(wNamespace, "w:r");
      const textNode = doc.createElementNS(wNamespace, "w:t");
      textNode.textContent = mathId;
      runNode.appendChild(textNode);
      
      // Replace the math node
      if (mathNode.parentNode) {
          mathNode.parentNode.replaceChild(runNode, mathNode);
      }
    }
  }

  const serializer = new XMLSerializer();
  const newXmlString = serializer.serializeToString(doc);

  zip.file("word/document.xml", newXmlString);

  const patchedBuffer = await zip.generateAsync({ type: "arraybuffer" });
  
  return { buffer: patchedBuffer, mathMap };
}

export async function convertDocxToQtiHtml(arrayBuffer) {
  // We use Mammoth.js to convert the DOCX file into HTML.
  
  // Preprocess to handle OMML
  const { buffer: patchedBuffer, mathMap } = await preprocessDocx(arrayBuffer);

  return mammoth.convertToHtml({ arrayBuffer: patchedBuffer })
    .then(function(result) {
        const html = result.value; 
        const messages = result.messages;
        console.log("Mammoth messages:", messages);
        // Defer replacement until after parsing to prevent textContent from stripping tags
        return { html, mathMap };
    })
    .catch(function(error) {
        console.error("Error converting DOCX to HTML:", error);
        throw error;
    });
}

/**
 * Parses the raw HTML generated by Mammoth into a structured array of questions.
 * 
 * Assumed Format (Common pattern):
 * - Questions might be paragraphs or lists. We'll look for standard text.
 * - Options are typically consecutive paragraphs or list items following a question.
 * - The correct option is usually marked, e.g., with bold text or an asterisk.
 * 
 * Since QTI 1.2 requires identifying questions and answers, this parser
 * uses a heuristic approach. 
 */
export function parseHtmlToQuestions(htmlString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlString, 'text/html');
    
    const questions = [];
    let currentQuestion = null;

    // Get all block-level elements that usually contain text in document order
    const elements = Array.from(doc.body.querySelectorAll('p, h1, h2, h3, h4, h5, h6, li, td'));

    for (let i = 0; i < elements.length; i++) {
        const el = elements[i];
        
        // Strip out any nested lists from the element's text so that outer LIs 
        // don't include the text of their inner option LIs.
        const clone = el.cloneNode(true);
        clone.querySelectorAll('ol, ul').forEach(list => list.remove());
        
        const plainText = clone.textContent.trim();
        const htmlContent = clone.innerHTML.trim();
        
        const hasImage = clone.querySelector('img') !== null;
        
        if (!plainText && !hasImage) continue;

        // Check if it looks like an option (e.g., "a. ", "A) ", "(a) ", "*a. ")
        const isOptionRegex = /^[\*\s]*\(?([a-zA-Z])[\.\)]\s+(.*)/;
        const match = plainText.match(isOptionRegex);
        
        // If it's an LI but it contains another list, it's definitely a question, not an option.
        const hasNestedList = el.querySelector('ol, ul') !== null;
        
        // We consider it an option if it explicitly matches letter formatting OR 
        // if it's a list item that does NOT contain a nested list.
        const isOption = match || (el.tagName === 'LI' && !hasNestedList);
        
        if (isOption && currentQuestion) {
            // HACK: If this is the very first option of the very first question,
            // we might have accidentally captured introductory text (titles, instructions).
            // Let's see if we can find the true start of the question by looking for a number.
            if (questions.length === 0 && currentQuestion.options.length === 0 && currentQuestion._rawBlocks) {
                const isQuestionStartRegex = /^((Q|Question)\s*)?\d+[\.\:\)]?\s+/i;
                const blocks = currentQuestion._rawBlocks;
                
                let startIndex = -1;
                for (let j = 0; j < blocks.length; j++) {
                    const plain = blocks[j].plainText.replace(/<[^>]+>/g, '').trim();
                    // It's the start of a question if it has explicit numbering OR if it is a list item
                    if (isQuestionStartRegex.test(plain) || blocks[j].tagName === 'LI') {
                        startIndex = j;
                        break;
                    }
                }
                
                if (startIndex > 0) {
                    // Discard everything before the true start of the first question!
                    const validBlocks = blocks.slice(startIndex).map(b => b.htmlContent);
                    currentQuestion.text = validBlocks.join('<br/>');
                }
            }

            // It's an option!
            let optionHtml = htmlContent;
            
            if (match) {
                // The regex matched a manual list prefix like "A) " or "a. "
                // Let's try to remove this prefix from the HTML so it doesn't render redundantly.
                const prefix = plainText.substring(0, plainText.indexOf(match[2]));
                
                const tempDiv = document.createElement('div');
                tempDiv.innerHTML = optionHtml;
                
                const walker = document.createTreeWalker(tempDiv, NodeFilter.SHOW_TEXT, null, false);
                const firstTextNode = walker.nextNode();
                if (firstTextNode) {
                    const nodeText = firstTextNode.textContent.trim();
                    const prefixTrim = prefix.trim();
                    if (nodeText.startsWith(prefixTrim)) {
                        firstTextNode.textContent = firstTextNode.textContent.replace(prefixTrim, '').trimStart();
                    } else if (nodeText === prefixTrim) {
                        firstTextNode.textContent = '';
                    }
                }
                optionHtml = tempDiv.innerHTML;
            }

            // Check for correct answer markers: {{ANS}}, bold, italics, or an asterisk
            let isCorrect = false;
            
            if (optionHtml.includes('{{ANS}}')) {
                isCorrect = true;
                optionHtml = optionHtml.replace('{{ANS}}', '').trim();
            } else if (plainText.includes('{{ANS}}')) {
                isCorrect = true;
            }

            if (!isCorrect) {
                isCorrect = el.querySelector('strong') !== null || 
                            el.querySelector('b') !== null || 
                            el.querySelector('em') !== null || 
                            plainText.includes('*');
                            
                if (plainText.startsWith('*')) {
                    // Strip asterisk from HTML
                    const tempDiv = document.createElement('div');
                    tempDiv.innerHTML = optionHtml;
                    const walker = document.createTreeWalker(tempDiv, NodeFilter.SHOW_TEXT, null, false);
                    const firstTextNode = walker.nextNode();
                    if (firstTextNode && firstTextNode.textContent.includes('*')) {
                        firstTextNode.textContent = firstTextNode.textContent.replace('*', '').trimStart();
                    }
                    optionHtml = tempDiv.innerHTML;
                }
            }

            currentQuestion.options.push({
                text: optionHtml,
                isCorrect: isCorrect
            });
        } else {
            // It's likely a question or a continuation of a question
            
            // If the current question already has options, and we see something that ISN'T an option,
            // that means we've hit the start of the NEXT question.
            if (currentQuestion && currentQuestion.options.length > 0) {
                questions.push(currentQuestion);
                currentQuestion = null;
            }
            
            if (!currentQuestion) {
                // Start a new question
                currentQuestion = {
                    id: 'q_' + Math.random().toString(36).substr(2, 9),
                    text: htmlContent,
                    options: [],
                    _rawBlocks: [{ plainText, htmlContent, tagName: el.tagName }]
                };
            } else {
                // Append HTML to the current question
                currentQuestion.text += '<br/>' + htmlContent;
                currentQuestion._rawBlocks.push({ plainText, htmlContent, tagName: el.tagName });
            }
        }
    }

    // Don't forget to push the very last question
    if (currentQuestion && currentQuestion.options.length > 0) {
        questions.push(currentQuestion);
    }

    return questions;
}
